# Generated by Django 5.2.5 on 2025-08-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_cart_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='products',
            name='created_at',
        ),
    ]
